### PR TITLE
Updated test script for status

### PR DESCRIPTION
**Pull request by asa1997**
Comments from pull #118 has been addressed.
Instructions for executing the test script,

1. move into your tests/commands/ folder under KOBman

2. Run the file test-kob-status.sh like a normal shell script with necessary parameters

   * `./test-kob-status.sh dummyenv 0.0.2`

    OUTPUT
    -------------
image

  * `./test-kob-status.sh dummyenv 0.0.3`

   OUTPUT
   ------------
image

 * Wrong version : `./test-kob-status.sh dummyenv 0.0.1` 

  OUTPUT
  ------------
image

### CODE REVIEW

**Comment by asa1997** [comment]
Please do ignore the file kobman-help.sh

**Comment by asa1997** [comment]
@panickervinod  @EtricKombat  Please do review the code

**Review by EtricKombat-zz — APPROVED** [review]
LGTM - This code change has been reviewed , and approved . 

image

**Comment by panickervinod** [comment]
@EtricKombat @asa1997  Please can you confirm what has failed is a failing test?  Will this get pulled into travis later?

**Comment by asa1997** [comment]
> @EtricKombat @asa1997 Please can you confirm what has failed is a failing test? Will this get pulled into travis later?

@panickervinod  Since the version 0.0.1 was non-existing, the install command wont execute properly.

**Comment by panickervinod** [comment]
@asa1997 The Kobman msg should be something like "0.0.1 version is not available". and if the message is correctly displayed , that is , if you assert your result with expected output , and both are found to be same. this test should pass and not fail.

**Pull request merged**
